### ISSUE TITLE
为什么不直接用store中的状态做登录判断呢？

### ISSUE THREAD

**Issue by kiyosunsun** [doterlin/vue-example-login#5]

**Comment by kiyosunsun** [comment]
另外 watch: {
    '$router': 'checkLogin'
  },好像根本监听不到this.$router.push('/index')的跳转

**Comment by doterlin** [comment]
store在刷新页面状态会被重置，需要每次一开始检查一下然后修改store状态。比较麻烦把。
>,好像根本监听不到this.$router.push('/index')的跳转
这个的话我之前试了可以的。你看看是不是版本问题。
